### ISSUE TITLE
While building the muser data app get crushed 

### ISSUE THREAD

**Issue by pradeepsalunke** [CUTR-at-USF/muser-data-analysis#3]
When we click on build muser data app get crushed and show the message "TypeError"

**Comment by pradeepsalunke** [comment]
3rd functionality with preloaded data works as expected.
But API limit is getting exhausted, this issue didn't appeared in previous test cycle.

**Comment by barbeau** [comment]
API limit issue is ticketed in #4, and I believe this issue is resolved in #1, so I'm closing this.

@pradeepsalunke Please re-open if this is still an issue.
